### ISSUE TITLE
Autogenerated tests failing

### ISSUE THREAD

**Issue by damianavila** [jupyter/cookiecutter-docker-stacks#3]
Hi folks,

I am trying to generate a Community image following the guide in the docs.
I have seen errors when I run the autogenerated tests on TravisCI.
Should be they working by default?
If the answer is yes, any guidance about where I could start looking into would be appreciated.

The failing TravisCI run lives here: https://travis-ci.org/umsi-mads/education-notebook/builds/484742142

@parente any hints?

Thanks!

**Comment by parente** [comment]
Thanks for the heads up Fixed in #4.
